#!/bin/sh
set -e

rb_files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.rb$' || true)
erb_files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.html\.erb$' || true)

if [ -n "$rb_files" ]; then
  echo "$rb_files" | xargs bin/standardrb --fix
  echo "$rb_files" | xargs git add
fi

if [ -n "$erb_files" ] && command -v herb >/dev/null 2>&1; then
  echo "$erb_files" | xargs herb fmt
  echo "$erb_files" | xargs git add
fi

js_files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.js$' || true)

if [ -n "$js_files" ] && command -v biome >/dev/null 2>&1; then
  echo "$js_files" | xargs biome format --write
  echo "$js_files" | xargs git add
fi
